#!/bin/bash

# CHAP="01"

for chapter in $CHAP; do
  for file in ./$chapter*/*; do
    if [ -f "$file" ]; then
      echo "$file"
      n="$(basename "$file" | grep -E "[0-9]" -o)"
      directions="$(dirname "$file")/directions/${n}_directions.txt"

      if [ -f $directions ]; then
        vim -OR "$file" "$directions"
        echo "Did you look up the answer?"
        select yn in "no" "yes"; do
          case $yn in
            no)
              echo "Great!"
              break
              ;;
            yes)
              mkdir "missed"
              cp {"$file","$directions"} "missed/"
              break
              ;;
          esac
        done
      else
        echo "Directions file '${directions}' does not exist."
        echo "Skipping exercise #${n}..."
      fi
    fi
  done
done
